stages:
  - build
  - push
  - deploy

build-docker-image:
  stage: build
  script:
    - docker build -t $ECR_REPOSITORY_URL_PROD:datapipeline-fe-dev .
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

pushing image to Dev Registry:
  stage: push
  before_script:
    - aws configure set aws_access_key_id $ECS_AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $ECS_AWS_SECRET_ACCESS_KEY
  script:
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_LOGIN_PASSWORD_PROD
    - docker push $ECR_REPOSITORY_URL_PROD:datapipeline-fe-dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

deploying to Dev Server:
  stage: deploy
  script:
    - \[ ! -f ~/.ssh/spectrapass-datapipeline-mumbai.pem \] && echo "$SPECTRAPASS_DATAPIPELINE_PRIVATEKEY" > ~/.ssh/spectrapass-datapipeline-mumbai.pem
    - chmod 400 ~/.ssh/spectrapass-datapipeline-mumbai.pem
    - ANSIBLE_CONFIG=.ansible/ansible.cfg ansible-playbook -i .ansible/inventories/dev/hosts .ansible/deploy.yml -e "APP_ENV=dev"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
